kind: pipeline
type: kubernetes
name: default

steps:
  - name: test-opa
    image: openpolicyagent/opa
    command:
      - test
      - --ignore=*.yaml
      - --ignore=*.json
      - -v
      - base
  - name: test-kustomize
    image: plugins/docker
    settings:
      dry_run: true
      repo: test
      dockerfile: Dockerfile.kustomize
  - name: test-template
    image: mikefarah/yq:4.9.8
    commands:
      - lib/template-match-src/template-match-src

trigger:
  event:
    exclude:
      - pull_request
