# blocks deletion of an object unless it is annotated with '$input.parameters.name: $input.parameters.value'
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: deleteannotationrequirement
spec:
  crd:
    spec:
      names:
        kind: DeleteAnnotationRequirement
      validation:
        openAPIV3Schema:
          required: [name, value]
          properties:
            name:
              type: string
            value:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package deleteannotationrequirement

        violation[{"msg": msg, "details": {
          "name": name,
          "kind": kind,
        }}] {
          name := input.review.object.metadata.name
          kind := input.review.kind.kind

          input.review.operation == "DELETE"
          not input.review.object.metadata.annotations[input.parameters.name] == input.parameters.value

          msg := sprintf("the %v '%v' must be annotated with '%v: \"%v\"' to be deleted", [kind, name, input.parameters.name, input.parameters.value])
        }
